# Generated by Django 4.2.7 on 2023-11-09 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('other_titles', models.CharField(max_length=128)),
                ('connect', models.CharField(max_length=128)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NW', 'New'), ('AC', 'Accepted'), ('PN', 'Pending'), ('RJ', 'Rejected')], default='NW', max_length=2)),
                ('winter_dif', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='1A', max_length=2)),
                ('spring_dif', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='1A', max_length=2)),
                ('summer_dif', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='1A', max_length=2)),
                ('autumn_dif', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='1A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=128, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('phone', models.IntegerField(unique=True)),
                ('autUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevelapp.perevaladded')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevelapp.images')),
            ],
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevelapp.users'),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='coord_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perevelapp.coord'),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='photo_id',
            field=models.ManyToManyField(through='perevelapp.PerevalImages', to='perevelapp.images'),
        ),
    ]
